### ISSUE TITLE
Maintain `pr12_metadata.pbtxt`

### ISSUE THREAD

**Issue by nicewook** [codingpot/pr12er#58]
need to make the file [pr12_metadata.pbtxt](https://github.com/codingpot/pr12er/blob/bbba5e8ecf8149e84ed8e786233fc1dbc6f4e333/server/internal/pr12_metadata.pbtxt) up to date and fresh

## Current status

- PR-001 ~ PR-207

The metadata of the following IDs do not have `video_metadata` field.
- 52, 81, 93, 137, 194, 198

**Comment by deep-diver** [comment]
현재 pr12 메타데이터 덤프를 뜨는 대상 저장소가 어디인가요? 

원본 저장소를 codingpot 쪽으로 fork 뜨고, 제가 TFKR 등에 공지를 올려서
집단지성을 활용해 내용을 채우면 어떨까 하는데요,,

어떻게 생각 하시나요?

**Comment by kkweon** [comment]
https://github.com/taeoh-kim/pr12

포크하는것보다 그냥 있는걸로 새로 만들어야 될 것 같아요.
마크다운보다 제대로 된 포맷으로

**Comment by deep-diver** [comment]
어떤 포맷으로 만들면 좋을까요? 일단 틀을 만들면, 다수가 힘을 합쳐 금방 채울 수 있을것도 같습니다 ㅎㅎ

**Comment by kkweon** [comment]
저는 prototext 좋을 것 같고 아니면 yaml 이요.

prototext > YAML > JSON > XML 선호도

```prototext
metadata {
  id: 1
  title: "Generative Adversarial Network"
  presenter: "Who Who WHo"
  keywords: "whowhowho"
  keywords: "wawawa"
}
metadata {
  id: 2
  // ...
}
```

```yaml
- id: 1
  title: Generative Adversarial Network
  presenter: WHOWHOWHO
  keywords:
  - whowhowho
  - wawaawa
  - god chansung

- id: 2
  title: ...
```
